### ISSUE TITLE
Date fields seriously does not work

### ISSUE THREAD

**Issue by cnrdh** [npolar/npdc-material#4]
Inpossible to enter a date, editor just gives back
dd.mm.åååå

Also the validation is far too restrictive given that ISO860 allows 
* "19" meaning 1900s
* "1971"
* "1971-07" (meaning July 1971)

**Comment by rexso** [comment]
format date in JSON-Schema doesn't comply with the ISO8601 standard,
but is stated to in the format of YYYY-MM-DD.

http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23

**Comment by cnrdh** [comment]
rexso, the JSON schema refers to ISO8601 for date times, so I just assumed it would for dates also.

Never mind that, I don't want to support "20" but I do want  to support "2015". Anyways I'm happy to do that with a pattern when needed. 

The problem with editing still remains (for YYYY-MM-DD)

**Comment by rexso** [comment]
The problem was in formula, and has now been fixed.
I'll add support for year as a format, but only for 4-digits due to the ambiguity of 2-digit years.

**Comment by rexso** [comment]
"date-fullyear" string format added.
